import { GetServerSideProps } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

// 'NEXT_PUBLIC_ANALYTICS_ID' can be used here as it's prefixed by 'NEXT_PUBLIC_'.
// It will be transformed at build time to `setupAnalyticsService('abcdefghijk')`.

export default function Home() {
  useEffect(() => {
    console.log("process.env Browser");
    console.log(process.env.NEXT_PUBLIC_DB_PASS);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>123456</h1>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  console.log(process.env);
  return {
    props: {}, // will be passed to the page component as props
  };
}
